### ISSUE TITLE
Exception: build failed

### ISSUE THREAD

**Issue by wanliyunyan** [XTLS/libXray#31]
```

root@****:~/libXray# python3 build/main.py android
['build/main.py', 'android']
go: creating new go.mod: module github.com/xtls/libxray
go: to add module requirements and sums:
        go mod tidy
go: finding module for package github.com/xtls/xray-core/common/cmdarg
go: finding module for package github.com/xtls/xray-core/app/log
go: finding module for package github.com/xtls/xray-core/app/router
go: finding module for package github.com/xtls/xray-core/transport/internet
go: finding module for package gopkg.in/yaml.v3
go: finding module for package github.com/xtls/xray-core/common
go: finding module for package github.com/xtls/xray-core/app/stats/command
go: finding module for package github.com/xtls/xray-core/common/log
go: finding module for package github.com/xtls/xray-core/common/uuid
go: finding module for package github.com/xtls/xray-core/core
go: finding module for package google.golang.org/grpc
go: finding module for package github.com/xtls/xray-core/main/distro/all
go: finding module for package google.golang.org/grpc/credentials/insecure
go: finding module for package google.golang.org/protobuf/encoding/protojson
go: finding module for package google.golang.org/protobuf/proto
go: found github.com/xtls/xray-core/transport/internet in github.com/xtls/xray-core v1.8.21
go: found github.com/xtls/xray-core/app/log in github.com/xtls/xray-core v1.8.21
go: found github.com/xtls/xray-core/common in github.com/xtls/xray-core v1.8.21
go: found github.com/xtls/xray-core/common/log in github.com/xtls/xray-core v1.8.21
go: found gopkg.in/yaml.v3 in gopkg.in/yaml.v3 v3.0.1
go: found github.com/xtls/xray-core/app/router in github.com/xtls/xray-core v1.8.21
go: found github.com/xtls/xray-core/app/stats/command in github.com/xtls/xray-core v1.8.21
go: found github.com/xtls/xray-core/common/cmdarg in github.com/xtls/xray-core v1.8.21
go: found github.com/xtls/xray-core/common/uuid in github.com/xtls/xray-core v1.8.21
go: found github.com/xtls/xray-core/core in github.com/xtls/xray-core v1.8.21
go: found github.com/xtls/xray-core/main/distro/all in github.com/xtls/xray-core v1.8.21
go: found google.golang.org/grpc in google.golang.org/grpc v1.65.0
go: found google.golang.org/grpc/credentials/insecure in google.golang.org/grpc v1.65.0
go: found google.golang.org/protobuf/encoding/protojson in google.golang.org/protobuf v1.34.2
go: found google.golang.org/protobuf/proto in google.golang.org/protobuf v1.34.2
go: added golang.org/x/mobile v0.0.0-20240716161057-1ad2df20a8b6
go: upgraded golang.org/x/mod v0.18.0 => v0.19.0
go: upgraded golang.org/x/tools v0.22.0 => v0.23.0
gomobile: go build -buildmode=c-shared -o=/tmp/gomobile-work-2368720822/android/src/main/jniLibs/x86/libgojni.so ./gobind failed: exit status 1
# github.com/xtls/libxray/log
/root/libXray/log/android.go:46:2: undefined: common
/root/libXray/log/android.go:46:14: undefined: xlog

Traceback (most recent call last):
  File "/root/libXray/build/main.py", line 30, in <module>
    builder.build()
  File "/root/libXray/build/app/android.py", line 23, in build
    raise Exception("build failed")
Exception: build failed

```

**Comment by wanliyunyan** [comment]
[android.go](https://github.com/XTLS/libXray/blob/main/log/android.go) 这个文件修改成这样就好了

```
import (
	xlog "github.com/xtls/xray-core/app/log"
	"github.com/xtls/xray-core/common"
	"github.com/xtls/xray-core/common/log"
)
```

**Comment by yiguous** [comment]
This modification has been reverted. Please compile again using latest codes.
