### ISSUE TITLE
Build failed. 

### ISSUE THREAD

**Issue by holly-gnolly** [XTLS/libXray#47]
please help me, I'm not familiar with go, I really need to build a libXray library )

```
root@v175739:~/xray/libXray# go version
go version go1.23.2 linux/amd64
root@v175739:~/xray/libXray# python3 build/main.py android
['build/main.py', 'android']
go: creating new go.mod: module github.com/xtls/libxray
go: to add module requirements and sums:
	go mod tidy
go: finding module for package gopkg.in/yaml.v3
go: finding module for package google.golang.org/protobuf/proto
go: found github.com/xtls/xray-core/transport/internet in github.com/xtls/xray-core v0.0.0-00010101000000-000000000000
go: found gopkg.in/yaml.v3 in gopkg.in/yaml.v3 v3.0.1
go: found github.com/xtls/xray-core/app/router in github.com/xtls/xray-core v0.0.0-00010101000000-000000000000
go: found github.com/xtls/xray-core/common/cmdarg in github.com/xtls/xray-core v0.0.0-00010101000000-000000000000
go: found github.com/xtls/xray-core/common/uuid in github.com/xtls/xray-core v0.0.0-00010101000000-000000000000
go: found github.com/xtls/xray-core/core in github.com/xtls/xray-core v0.0.0-00010101000000-000000000000
go: found github.com/xtls/xray-core/main/distro/all in github.com/xtls/xray-core v0.0.0-00010101000000-000000000000
go: found google.golang.org/protobuf/proto in google.golang.org/protobuf v1.35.1
go: -d flag is deprecated. -d=true is a no-op
go: added golang.org/x/mobile v0.0.0-20241016134751-7ff83004ec2c
go: upgraded golang.org/x/mod v0.18.0 => v0.21.0
go: upgraded golang.org/x/tools v0.22.0 => v0.26.0
gomobile: go mod tidy failed: exit status 1
go: found github.com/xtls/libxray in github.com/xtls/libxray v0.0.0-00010101000000-000000000000
go: gobind/gobind imports
	github.com/xtls/libxray imports
	github.com/xtls/libxray/xray imports
	github.com/xtls/xray-core/main/distro/all imports
	github.com/xtls/xray-core/app/log/command imports
	google.golang.org/grpc/status imports
	google.golang.org/genproto/googleapis/rpc/status: ambiguous import: found package google.golang.org/genproto/googleapis/rpc/status in multiple modules:
	google.golang.org/genproto v0.0.0-20230110181048-76db0878b65f (/root/go/pkg/mod/google.golang.org/genproto@v0.0.0-20230110181048-76db0878b65f/googleapis/rpc/status)
	google.golang.org/genproto/googleapis/rpc v0.0.0-20240814211410-ddb44dafa142 (/root/go/pkg/mod/google.golang.org/genproto/googleapis/rpc@v0.0.0-20240814211410-ddb44dafa142/status)
go: gobind/gobind imports
	github.com/xtls/libxray imports
	github.com/xtls/libxray/xray imports
	github.com/xtls/xray-core/main/distro/all imports
	github.com/xtls/xray-core/app/log/command imports
	google.golang.org/grpc/codes tested by
	google.golang.org/grpc/codes.test imports
	google.golang.org/genproto/googleapis/rpc/code: ambiguous import: found package google.golang.org/genproto/googleapis/rpc/code in multiple modules:
	google.golang.org/genproto v0.0.0-20230110181048-76db0878b65f (/root/go/pkg/mod/google.golang.org/genproto@v0.0.0-20230110181048-76db0878b65f/googleapis/rpc/code)
	google.golang.org/genproto/googleapis/rpc v0.0.0-20240814211410-ddb44dafa142 (/root/go/pkg/mod/google.golang.org/genproto/googleapis/rpc@v0.0.0-20240814211410-ddb44dafa142/code)
go: gobind/gobind imports
	github.com/xtls/libxray imports
	github.com/xtls/libxray/xray imports
	github.com/xtls/xray-core/main/distro/all imports
	github.com/xtls/xray-core/app/log/command imports
	google.golang.org/grpc/status tested by
	google.golang.org/grpc/status.test imports
	google.golang.org/genproto/googleapis/rpc/errdetails: ambiguous import: found package google.golang.org/genproto/googleapis/rpc/errdetails in multiple modules:
	google.golang.org/genproto v0.0.0-20230110181048-76db0878b65f (/root/go/pkg/mod/google.golang.org/genproto@v0.0.0-20230110181048-76db0878b65f/googleapis/rpc/errdetails)
	google.golang.org/genproto/googleapis/rpc v0.0.0-20240814211410-ddb44dafa142 (/root/go/pkg/mod/google.golang.org/genproto/googleapis/rpc@v0.0.0-20240814211410-ddb44dafa142/errdetails)

Traceback (most recent call last):
  File "/root/xray/libXray/build/main.py", line 32, in <module>
    builder.build()
  File "/root/xray/libXray/build/app/android.py", line 22, in build
    raise Exception("build failed")
Exception: build failed

```

**Comment by yuhan6665** [comment]
https://github.com/2dust/AndroidLibXrayLite/pull/59
