### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by wanliyunyan** [XTLS/libXray#57]
Android和ios都报这个错误
```
:~/libXray# python3 build/main.py android
['build/main.py', 'android']
go: creating new go.mod: module github.com/xtls/libxray
go: to add module requirements and sums:
        go mod tidy
go: finding module for package google.golang.org/protobuf/proto
go: finding module for package gopkg.in/yaml.v3
go: found github.com/xtls/xray-core/infra/conf in github.com/xtls/xray-core v0.0.0-00010101000000-000000000000
go: found github.com/xtls/xray-core/transport/internet in github.com/xtls/xray-core v0.0.0-00010101000000-000000000000
go: found github.com/xtls/xray-core/common/net in github.com/xtls/xray-core v0.0.0-00010101000000-000000000000
go: found github.com/xtls/xray-core/proxy/vless in github.com/xtls/xray-core v0.0.0-00010101000000-000000000000
go: found gopkg.in/yaml.v3 in gopkg.in/yaml.v3 v3.0.1
go: found github.com/xtls/xray-core/app/router in github.com/xtls/xray-core v0.0.0-00010101000000-000000000000
go: found github.com/xtls/xray-core/common/cmdarg in github.com/xtls/xray-core v0.0.0-00010101000000-000000000000
go: found github.com/xtls/xray-core/common/uuid in github.com/xtls/xray-core v0.0.0-00010101000000-000000000000
go: found github.com/xtls/xray-core/core in github.com/xtls/xray-core v0.0.0-00010101000000-000000000000
go: found github.com/xtls/xray-core/main/distro/all in github.com/xtls/xray-core v0.0.0-00010101000000-000000000000
go: found google.golang.org/protobuf/proto in google.golang.org/protobuf v1.36.0
# github.com/xtls/libxray/share
share/clash_meta.go:384:26: undefined: conf.HTTPConfig
share/clash_meta.go:389:19: streamSettings.HTTPSettings undefined (type *conf.StreamConfig has no field or method HTTPSettings)
share/clash_meta.go:396:19: streamSettings.GRPCConfig undefined (type *conf.StreamConfig has no field or method GRPCConfig)
share/generate_share.go:291:21: streamSettings.GRPCConfig undefined (type *conf.StreamConfig has no field or method GRPCConfig)
share/generate_share.go:294:26: streamSettings.GRPCConfig undefined (type *conf.StreamConfig has no field or method GRPCConfig)
share/generate_share.go:300:33: streamSettings.GRPCConfig undefined (type *conf.StreamConfig has no field or method GRPCConfig)
share/generate_share.go:304:31: streamSettings.GRPCConfig undefined (type *conf.StreamConfig has no field or method GRPCConfig)
share/generate_share.go:309:21: streamSettings.HTTPSettings undefined (type *conf.StreamConfig has no field or method HTTPSettings)
share/generate_share.go:312:26: streamSettings.HTTPSettings undefined (type *conf.StreamConfig has no field or method HTTPSettings)
share/generate_share.go:316:26: streamSettings.HTTPSettings undefined (type *conf.StreamConfig has no field or method HTTPSettings)
share/generate_share.go:316:26: too many errors
Traceback (most recent call last):
  File "/root/libXray/build/main.py", line 32, in <module>
    builder.build()
  File "/root/libXray/build/app/android.py", line 13, in build
    self.before_build()
  File "/root/libXray/build/app/android.py", line 9, in before_build
    super().before_build()
  File "/root/libXray/build/app/build.py", line 113, in before_build
    self.download_geo()
  File "/root/libXray/build/app/build.py", line 64, in download_geo
    raise Exception("download_geo failed")
Exception: download_geo failed
```

**Comment by yiguous** [comment]
Don't use the pre-release version. This lib only keeps compatible with Xray-core's stable version. Currently, it should be [v24.11.30](https://github.com/XTLS/Xray-core/releases/tag/v24.11.30).
